### ISSUE TITLE
yascroll acts strangely with visual-line-mode on

### ISSUE THREAD

**Issue by ylluminarious** [m2ym/yascroll-el#19]
No matter which style I choose for `yascroll:scroll-bar`, the scrollbar always acts strangely with `visual-line-mode` turned on. This is a problem because I, along with many others, use this mode frequently and / or globally. It's rather hard to explain the effect that occurs [so here's a screencast demonstrating the problem.](https://cl.ly/0g3W371O0m1m/yascroll_with_visual_line_mode_on.mp4)

I'm on GNU Emacs 25.1.1 and OS X 10.12.3.

**Comment by ylluminarious** [comment]
@m2ym Any thoughts on how to resolve this?

**Comment by m2ym** [comment]
Maybe miscalculation of the scrollbar thumb. Could I see any reproducible test case file?

**Comment by ylluminarious** [comment]
@m2ym All that you really need to reproduce the issue is some text that reaches the window edge and then wraps around. Here's what I used to generate some such text: http://www.lipsum.com

**Comment by ylluminarious** [comment]
@m2ym Did that help or do you need more information?

**Comment by m2ym** [comment]
Yes, thanks.

**Comment by ylluminarious** [comment]
@m2ym Any progress on this? No rush, just wondering.

**Comment by m2ym** [comment]
I couldn't see any big glitches (but a small one) on my machine. Could I ask you find a minimum reproducible configuration of the problem by disabling some major/minor modes, or enabling them from vanilla.

**Comment by m2ym** [comment]
Ah, I have a mistake. I can see the problem now.

**Comment by ylluminarious** [comment]
Alright, thanks for the update. Let me know if you need any further information or testing.

**Comment by m2ym** [comment]
Fixed. Feel free to reopen the ticket if you still have the problem.

**Comment by ylluminarious** [comment]
@m2ym That seems to have fixed the problem. Thanks so much!
